[book]
authors = ["smileluck"]
language = "en"
multilingual = false
src = "src"
title = "SmileX-Life"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
site-url = "/SmileX-Life/"
git-repository-url = "https://github.com/smileluck/SmileX-Life"